### ISSUE TITLE
problem with add new db

### ISSUE THREAD

**Issue by kni322** [starburstdata/metabase-driver#105]
when i add new db to metabase (v 0.45.2.1) then i get an error **"No method in multimethod 'connection-details->spec' for dispatch value: :starburst"**

metabase-driver v 3.0.1

**Comment by hovaesco** [comment]
Metabase by default does not contain the Starburst driver (it should be downloaded and installed separately).

**Comment by kni322** [comment]
I installed this starburst-3.0.1.metabase-driver.jar  from https://github.com/starburstdata/metabase-driver/releases/tag/3.0.1 or need to install something else? 

Need Metabase Enterprise  or Metabase Open Source Edition?
