### ISSUE TITLE
Upgrade to Metabase 1.48

### ISSUE THREAD

**Issue by lpoulain** [starburstdata/metabase-driver#119]
Make sure the driver works with Metabase 1.48.0, and that all deprecated methods have been replaced

**Comment by samssh** [comment]
Hello everyone,

Has there been any progress on this issue? Do we know when the version compatible with Metabase 1.48 will be available for release?

**Comment by lpoulain** [comment]
Yes, there's been progress albeit slower than expected. In the meantime, the current version should work with Metabase 1.48 as the changes have mostly been around new tests introduced by Metabase.
