### ISSUE TITLE
Cannot connect to PrestoDB

### ISSUE THREAD

**Issue by huynhphuong10284** [starburstdata/metabase-driver#124]
I'm using "starburst-4.1.0.metabase-driver.jar" and want to connect to PrestoDB (0.283), the connection is not successful. The following is an error displays on UI:

"Error executing query: Error starting query at http://xx.xx.xx.xx:9188/v1/statement returned an invalid response: JsonResponse{statusCode=400, headers={content-length=[16], content-type=[text/plain], date=[Tue, 26 Mar 2024 04:41:14 GMT]}, hasValue=false} [Error: User must be set]"

For error in Metabase (v0.48.2), please refer to attached file.

From release document (https://github.com/starburstdata/metabase-driver/releases), I only see you built for Enterprise. Could you please give more information about Metabase open source and how about my bug?

Thanks,
Phuong
[metabase.log](https://github.com/starburstdata/metabase-driver/files/14752575/metabase.log)

**Comment by paoliniluis** [comment]
Hi, why can't you use the native Presto metabase driver instead of using the starburst one. Remember that Trino and Presto diverged

**Comment by lpoulain** [comment]
This driver has only been written and designed for Trino. If you want to use it we recommend you switch to Trino.

**Comment by huynhphuong10284** [comment]
> This driver has only been written and designed for Trino. If you want to use it we recommend you switch to Trino.

Thanks man.
