### ISSUE TITLE
Role field UI bug when adding a Starburst database

### ISSUE THREAD

**Issue by lpoulain** [starburstdata/metabase-driver#77]
When adding a Starburst database, the optional Role field is put below the Advanced section. However, when expanding that section, the Role field finds itself inside the advanced fields

**Comment by leniartek** [comment]
Please move the `Role` field before the advanced section.

**Comment by lpoulain** [comment]
Here is the updated look

![Screenshot 2023-03-13 at 11 02 14 AM](https://user-images.githubusercontent.com/2676310/224741789-d75d193d-3f17-4a15-9d7e-3ffa25156229.png)

**Comment by leniartek** [comment]
Looks good, thank you!
