### ISSUE TITLE
Upgrade to latest metabase version

### ISSUE THREAD

**Issue by andrewdibiasio6** [starburstdata/metabase-driver#86]
we are currently on 1.45.0, lets use the latest metabase version. see: https://github.com/starburstdata/metabase-driver/blob/main/app_versions.json

**Comment by torshind** [comment]
This is just to let you know that I'm on 0.46.2 right now, and I'm getting this warning:
```
query-processor.deprecated :: Warning: Driver :starburst is using Honey SQL 1. This method was deprecated in 0.46.0 and will be removed in a future release.
```

**Comment by andrewdibiasio6** [comment]
>This is just to let you know that I'm on 0.46.2 right now, and I'm getting this warning:

The metabase API changes with each minor version update. I would expect to see errors using a different version.
