### ISSUE TITLE
Upgrade to Honey SQL 2

### ISSUE THREAD

**Issue by lpoulain** [starburstdata/metabase-driver#88]
Replace calls to the Honey SQL library to Honey SQL 2 as described in https://www.metabase.com/docs/master/developers-guide/driver-changelog

**Comment by andrewdibiasio6** [comment]
This needs to be done in https://github.com/starburstdata/metabase-driver/issues/86, I will close as a duplicate.

**Comment by andrewdibiasio6** [comment]
NM, it is not required to be upgraded in 1.46.x
